replace elipses with three periods
elipses was causing exceptions when trying to print
the help message:
  UnicodeEncodeError: 'latin-1' codec can't encode
  character '\u2026' in position 345: ordinal not in range(256)
Replaced them with three periods